@startuml
actor Owner as owner
actor Costumer as customer
actor Farmer as farmer
actor Butcher as butcher
actor "Delivery\nService" as delivery
participant "Crowdfunding\nContract" as crowdContract
participant "Supply Chain\nContract" as supplyContract

owner --> crowdContract: Call create function
activate crowdContract
crowdContract --> crowdContract: Validate Input
crowdContract --> crowdContract: Save Campaign
crowdContract --> crowdContract: Save Boxes
deactivate crowdContract

customer --> crowdContract: call buy function
activate crowdContract
crowdContract --> crowdContract: Validate Input
crowdContract --> crowdContract: Add Sell Reference
crowdContract --> crowdContract: Update Campaign\nMetadata

alt All Boxes have been sold
    activate supplyContract
    crowdContract -> supplyContract: Start Supply Chain

    alt Supply Chain has finished
        supplyContract -> crowdContract: Notify
    end
    deactivate supplyContract

    crowdContract -> farmer: Pay out
    crowdContract -> butcher: Pay out
    crowdContract -> delivery: Pay out
end
deactivate crowdContract
@enduml
