@startuml

partition Crowdfunding {

  (*) --> "Campaign Owner\ncreates Campaign"
  -down-> "Consumer buys Box" as buyBox
  -down-> if "Campaign has\nstopped?" then
    -right->[Yes] (*)
  else
    -down->[No] if "All Boxes sold?" then
      -down->[Yes] "Start Supply Chain" as startSupply
    else
      -left->[No] buyBox
    endif
  endif
}

partition "Supply Chain" {
  startSupply -right-> "Farmer delivers Animal to\nButcher"
  --> "Butcher processes Animal"
  --> "Butcher processes Boxes"
  --> "Butcher delivers Boxes\nto Delivery Service"
  --> "Delivery Service delivers\nBox to Consumer" as delivery
}

partition Crowdfunding {
  delivery -up-> "Pay out all stakeholders"
  --> (*)
}

@enduml
